import {
  EmitContext,
  emitFile,
  Model,
  Interface,
  Namespace,
  Program,
} from "@typespec/compiler";
import {
  collectServices,
  RpcInfo,
  ServiceInfo,
  toSnakeCase,
  isStreamOp,
} from "@speconn/typespec-emitter-core";

export type EmitterOptions = {
  "emitter-output-dir": string;
};

async function emitPython(program: Program, services: ServiceInfo[], outputDir: string): Promise<void> {
  const promises: Promise<void>[] = [];

  for (const svc of services) {
    if (svc.rpcs.length === 0) continue;
    const snake = toSnakeCase(svc.serviceName);
    const typesModule = `${snake}_types`;
    const reqCodec = (rpc: RpcInfo) => rpc.inputType ? `${rpc.inputType.name}Codec` : "None";
    const resCodec = (rpc: RpcInfo) => rpc.outputType ? `${rpc.outputType.name}Codec` : "None";
    const reqType = (rpc: RpcInfo) => rpc.inputType?.name ?? "Any";
    const resType = (rpc: RpcInfo) => rpc.outputType?.name ?? "Any";

    // ---- server ----
    const server: string[] = [];
    server.push("# Generated by @speconn/typespec-emitter-python. DO NOT EDIT.\n");
    server.push("from __future__ import annotations");
    server.push("from speconn import SpeconnRouter, SpeconnContext");
    server.push(`from ${typesModule} import *\n`);
    server.push(`def create_router(service, interceptors=None) -> SpeconnRouter:`);
    server.push(`    router = SpeconnRouter(interceptors=interceptors)`);
    for (const rpc of svc.rpcs) {
      const method = rpc.isStream ? "server_stream" : "unary";
      server.push(`    router.${method}("${rpc.path}", ${reqCodec(rpc)}, ${resCodec(rpc)})(service.${rpc.name})`);
    }
    server.push(`    return router\n`);

    // ---- client ----
    const client: string[] = [];
    client.push("# Generated by @speconn/typespec-emitter-python. DO NOT EDIT.\n");
    client.push("from __future__ import annotations");
    client.push("from typing import Any");
    client.push("from speconn import SpeconnClient, SpeconnTransport, CallOptions, Response, StreamResponse");
    client.push(`from ${typesModule} import *\n`);
    client.push(`class ${svc.serviceName}Client:`);
    client.push(`    def __init__(self, base_url: str, transport: SpeconnTransport | None = None) -> None:`);
    for (const rpc of svc.rpcs) {
      client.push(`        self._${rpc.name} = SpeconnClient(base_url, "${rpc.path}", transport)`);
    }
    for (const rpc of svc.rpcs) {
      if (rpc.isStream) {
        client.push(`    async def ${rpc.name}(self, req: ${reqType(rpc)}, *, headers: dict[str, str] | None = None, timeout_ms: int | None = None) -> StreamResponse[${resType(rpc)}]:`);
        client.push(`        return await self._${rpc.name}.stream(req, ${reqCodec(rpc)}, ${resCodec(rpc)}, CallOptions(headers=headers or {}, timeout_ms=timeout_ms))`);
      } else {
        client.push(`    async def ${rpc.name}(self, req: ${reqType(rpc)}, *, headers: dict[str, str] | None = None, timeout_ms: int | None = None) -> Response[${resType(rpc)}]:`);
        client.push(`        return await self._${rpc.name}.call(req, ${reqCodec(rpc)}, ${resCodec(rpc)}, CallOptions(headers=headers or {}, timeout_ms=timeout_ms))`);
      }
    }
    client.push('');

    promises.push(emitFile(program, { path: `${outputDir}/${snake}_server.py`, content: server.join("\n") }));
    promises.push(emitFile(program, { path: `${outputDir}/${snake}_client.py`, content: client.join("\n") }));
  }
  await Promise.all(promises);
}

export async function $onEmit(context: EmitContext<EmitterOptions>) {
  const services = collectServices(context.program);
  await emitPython(context.program, services, context.emitterOutputDir);
}
